import { load } from '../../core/storage.js';
import { STORAGE_KEYS } from '../../core/constants.js';
import { inventoryStatus } from '../../core/utils.js';

function getInventory(){ return load(STORAGE_KEYS.MAYOREO_INVENTORY, []); }
function getClients(){ return load(STORAGE_KEYS.MAYOREO_CLIENTS, []); }
function getSales(){ return load(STORAGE_KEYS.MAYOREO_SALES, []); }
function money(n){ return `$${Number(n||0).toFixed(2)}`; }
function todayKey(){ return new Date().toISOString().slice(0,10); }
export function renderModule(){ const inventory=getInventory(), clients=getClients(), sales=getSales(); const today=todayKey(); const salesToday=sales.filter(s=>String(s.fecha||'').slice(0,10)===today); const totalToday=salesToday.reduce((a,s)=>a+Number(s.total||0),0); const lowStock=inventory.filter(i=>Number(i.stock||0)<=Number(i.stockMinimo||0)); const caducar=inventory.filter(i=>inventoryStatus(i).label!=='Vigente'); const topProducts=[...new Map(sales.flatMap(s=>(s.items||[]).map(i=>[i.nombre,0]))).keys()].slice(0,5); return `<div class="page"><section class="grid grid-4"><article class="card"><div class="muted">Ventas hoy</div><div class="kpi-value">${money(totalToday)}</div><div class="kpi-meta">Bloque mayoreo</div></article><article class="card"><div class="muted">Tickets hoy</div><div class="kpi-value">${salesToday.length}</div><div class="kpi-meta">Ventas registradas</div></article><article class="card"><div class="muted">Clientes activos</div><div class="kpi-value">${clients.filter(c=>c.activo!==false).length}</div><div class="kpi-meta">Base mayoreo</div></article><article class="card"><div class="muted">Inventario mayoreo</div><div class="kpi-value">${inventory.length}</div><div class="kpi-meta">Productos separados</div></article></section><section class="grid grid-2"><article class="card"><h3>Alertas mayoreo</h3><div class="status-list"><div class="status-item"><span>Stock bajo</span><span class="status-tag danger">${lowStock.length}</span></div><div class="status-item"><span>Por caducar / vencidos</span><span class="status-tag warn">${caducar.length}</span></div><div class="status-item"><span>Ventas acumuladas</span><span class="status-tag soft-blue">${money(sales.reduce((a,s)=>a+Number(s.total||0),0))}</span></div></div></article><article class="card"><h3>Resumen</h3><div class="status-list">${lowStock.slice(0,3).map(i=>`<div class="status-item"><span>${i.nombre}</span><span class="status-tag danger">Stock ${i.stock}</span></div>`).join('') || '<div class="status-item"><span class="muted">Sin alertas de stock bajo.</span></div>'}${caducar.slice(0,3).map(i=>`<div class="status-item"><span>${i.nombre}</span><span class="status-tag warn">${inventoryStatus(i).label}</span></div>`).join('')}${topProducts.length?`<div class="status-item"><span>Productos con movimiento</span><b>${topProducts.length}</b></div>`:''}</div></article></section></div>`; }
