export const state = {
  route: 'dashboard',
  user: null,
  menuCollapsed: false,
  mobileMenu: false,
  salesQuery: '',
  inventoryQuery: '',
  bodegaQuery: '',
  comprasQuery: '',
  gastosQuery: '',
  clientsQuery: '',
  selectedManagedUserId: '',
  editingInventoryId: '',
  editingBodegaId: '',
  editingCompraId: '',
  editingGastoId: '',
  editingClientId: '',
  historyQuery: '',
  reportQuery: '',
  reportPayment: '',
  reportFrom: '',
  reportTo: '',
  cart: { items: [], cliente: 'Mostrador', pago: 'Efectivo', receta: '', extraLabel: '', extraAmount: 0 },
  lastSale: '',
  webQuery: '',
  webCategory: 'Todas',
  webCart: [],
  mayoreoSalesQuery: '',
  mayoreoInventoryQuery: '',
  mayoreoClientsQuery: '',
  mayoreoCart: { items: [], cliente: '', pago: 'Transferencia', nota: '', extraLabel: '', extraAmount: 0 },
  mayoreoLastSale: '',
  editingMayoreoInventoryId: '',
  editingMayoreoClientId: '',
  mayoreoHistoryQuery: ''
};
