import { state } from '../../core/state.js';
import { load } from '../../core/storage.js';
import { STORAGE_KEYS } from '../../core/constants.js';

function getSales(){ return load(STORAGE_KEYS.MAYOREO_SALES, []); }
function money(n){ return `$${Number(n||0).toFixed(2)}`; }
function fmtDate(iso){ const d=new Date(iso); return isNaN(d)?(iso||''):d.toLocaleString('es-MX',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}); }
function filtered(){ const q=(state.mayoreoHistoryQuery||'').trim().toLowerCase(); const sales=getSales(); if(!q) return sales; return sales.filter(s=>[s.folio,s.cliente,s.pago].some(v=>String(v||'').toLowerCase().includes(q)) || (s.items||[]).some(i=>String(i.nombre||'').toLowerCase().includes(q))); }
function detail(sale){ if(!sale) return `<div class="status-item"><span class="muted">Todavía no hay ventas mayoreo.</span></div>`; return `<div class="status-list"><div class="status-item"><span>Folio</span><b>${sale.folio}</b></div><div class="status-item"><span>Cliente</span><b>${sale.cliente}</b></div><div class="status-item"><span>Fecha</span><b>${fmtDate(sale.fecha)}</b></div><div class="status-item"><span>Pago</span><b>${sale.pago}</b></div><div class="status-item"><span>Subtotal</span><b>${money(sale.subtotal)}</b></div><div class="status-item"><span>Extra</span><b>${money(sale.extraAmount)}</b></div><div class="status-item"><span>Total</span><b>${money(sale.total)}</b></div></div><div class="table-wrap" style="margin-top:14px;"><table style="min-width:100%;"><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Importe</th></tr></thead><tbody>${(sale.items||[]).map(i=>`<tr><td>${i.nombre}</td><td>${i.cantidad}</td><td>${money(i.precio)}</td><td>${money(i.cantidad*i.precio)}</td></tr>`).join('')}</tbody></table></div>`; }
export function renderModule(){ const sales=filtered(); const total=sales.reduce((a,s)=>a+Number(s.total||0),0); const extras=sales.reduce((a,s)=>a+Number(s.extraAmount||0),0); return `<div class="page"><section class="grid grid-4"><article class="card"><div class="muted">Tickets mayoreo</div><div class="kpi-value">${sales.length}</div><div class="kpi-meta">Registros filtrados</div></article><article class="card"><div class="muted">Ventas acumuladas</div><div class="kpi-value">${money(total)}</div><div class="kpi-meta">Total filtrado</div></article><article class="card"><div class="muted">Extras</div><div class="kpi-value">${money(extras)}</div><div class="kpi-meta">Flete u otros cargos</div></article><article class="card"><div class="muted">Clientes</div><div class="kpi-value">${new Set(sales.map(s=>s.cliente)).size}</div><div class="kpi-meta">Con compras</div></article></section><section class="grid" style="grid-template-columns:1.08fr .92fr; align-items:start;"><article class="card"><div class="toolbar-row"><div><h3 style="margin:0;">Historial mayoreo</h3><p class="muted" style="margin:6px 0 0;">Consulta por folio, cliente, producto o pago.</p></div></div><div class="input-group" style="margin-bottom:16px;"><label for="mayoreoHistorySearch">Buscar en historial mayoreo</label><input id="mayoreoHistorySearch" value="${state.mayoreoHistoryQuery||''}" placeholder="Ej. MV-240501, clínica, transferencia" /></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Folio</th><th>Cliente</th><th>Pago</th><th>Total</th><th>Detalle</th></tr></thead><tbody>${sales.map((s,idx)=>`<tr><td>${fmtDate(s.fecha)}</td><td>${s.folio}</td><td>${s.cliente}</td><td>${s.pago}</td><td>${money(s.total)}</td><td><button class="btn btn-secondary small-btn mayoreo-history-detail-btn" data-idx="${idx}">Ver</button></td></tr>`).join('') || '<tr><td colspan="6" class="muted">No hay ventas mayoreo para esta búsqueda.</td></tr>'}</tbody></table></div></article><article class="card" id="mayoreoHistoryDetailWrap"><h3>Detalle de venta mayoreo</h3><p class="muted">Selecciona un registro para ver el desglose.</p>${detail(sales[0])}</article></section></div>`; }
export function bindMayoreoHistorial(render){ document.getElementById('mayoreoHistorySearch')?.addEventListener('input', e=>{ state.mayoreoHistoryQuery=e.target.value; render(); }); document.querySelectorAll('.mayoreo-history-detail-btn').forEach(btn=>btn.addEventListener('click', ()=>{ const sale=filtered()[Number(btn.dataset.idx)]; const wrap=document.getElementById('mayoreoHistoryDetailWrap'); if(!wrap||!sale) return; wrap.innerHTML=`<h3>Detalle de venta mayoreo</h3><p class="muted">Desglose del folio seleccionado.</p>${detail(sale)}`; })); }
